version: '3.8'
services:
  text-detection-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./ocr_output:/app/ocr_output
      - ./mlruns:/app/mlruns
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  ocr_output:
  mlruns: