apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-detection-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: text-detection-api
  template:
    metadata:
      labels:
        app: text-detection-api
    spec:
      containers:
      - name: text-detection-api
        image: text-detection-api:latest
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: mlruns-storage
          mountPath: /app/mlruns
      volumes:
      - name: mlruns-storage
        hostPath:
          path: /path/to/your/mlruns  # Replace with the path to your mlruns directory
---
apiVersion: v1
kind: Service
metadata:
  name: text-detection-api-service
spec:
  selector:
    app: text-detection-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer